### Инициализация данных

In [1]:
from main import MusicRecommend

mr = MusicRecommend(
    path_triplets='data/p02_train_triplets.txt/train_triplets.txt',
    path_tracks='data/p02_unique_tracks.txt',
    path_majority='data/p02_msd_tagtraum_cd2.cls',
    path_track_words='data/p02_mxm_dataset_train.txt/mxm_dataset_train.txt'
)

triplets = mr.triplets
tracks = mr.tracks
majority = mr.majority
vocab_dict = mr.vocab_dict
track_words = mr.track_words

### 250 лучших треков

In [2]:
top_250_tracks = mr.top_250_tracks()
top_250_tracks.head()

,song_id,artist,title,play_count
0,SOBONKR12A58A7A7E0,Dwight Yoakam,You're The One,726885
1,SOAUWYT12A81C206F1,Björk,Undo,648239
2,SOSXLTC12AF72A7F54,Kings Of Leon,Revelry,527893
3,SOFRQTD12A81C233C0,Harmonia,Sehr kosmisch,425463
4,SOEGIYH12A6D4FC0E3,Barry Tuckwell/Academy of St Martin-in-the-Fie...,Horn Concerto No. 4 in E flat K495: II. Romanc...,389880

### 100 лучших треков по жанрам

In [3]:
top_100_rock_tracks = mr.top_100_genre(majority_genre='Rock')
top_100_rock_tracks.head()

              song_id         artist          title  play_count
0  SOAUWYT12A81C206F1          Björk           Undo      648239
1  SOSXLTC12AF72A7F54  Kings Of Leon        Revelry      527893
2  SOFRQTD12A81C233C0       Harmonia  Sehr kosmisch      425463
3  SONYKOW12AB01849C9    OneRepublic        Secrets      292642
4  SOUFTBI12AB0183F65       Tub Ring        Invalid      268353

In [4]:
top_100_electronic_tracks = mr.top_100_genre(majority_genre='Electronic')
top_100_electronic_tracks.head()

,song_id,artist,title,play_count
0,SOBRHVR12A8C133F35,Southside Spinners,Luvstruck,84225
1,SOVDLZN12AB0185BEA,The Black Keys,Tighten Up,81179
2,SOEPZQS12A8C1436C7,Deadmau5,Ghosts 'n' Stuff (Original Instrumental Mix),63951
3,SOAFTRR12AF72A8D4D,Daft Punk,Harder Better Faster Stronger,63170
4,SOJSXJY12A8C13E32E,Clara Hill,Clara meets Slope - Hard To Say,58887

### Коллекции

In [5]:
top_50_war = mr.top_50_by_word('war')
top_50_war.head(10)

,song_id,artist,title,play_count
0,SONQCXC12A6D4F6A37,Sheena Easton,Strut (1993 Digital Remaster),115134
1,SOBPKPW12A6701E8F9,Eminem / Nate Dogg,'Till I Collapse,44305
2,SOLWRZI12A6D4FC4F0,Creedence Clearwater Revival,Fortunate Son,34506
3,SOGRAGY12A6D4F7248,O.G.C.,Gunn Clapp,33897
4,SOVJHCB12A8AE4636E,John Mayer,Waiting On The World To Change,24455
5,SOUPMLF12A6701EAFE,Guns N' Roses,Civil War,22893
6,SOICNON12A8C140437,Coldplay,Life In Technicolor ii,22285
7,SOJTDUS12A6D4FBF0E,Aesop Rock,None Shall Pass (Main),19168
8,SONPEXU12A8C1451BD,Rise Against,Hero Of War,18939
9,SOYBHSI12A58A7D58B,Hollywood Undead,Young,16920

In [6]:
mr.train_w2v_model()
top_50_war_w2v = mr.top_50_by_word('war', use_w2v=True)
top_50_war_w2v.head(10)

Similar_words: ['hell', 'death', 'set', 'best', 'seen', 'hate', 'under', 'truth', 'rise', 'wind']

,song_id,artist,title,play_count
0,SONYKOW12AB01849C9,OneRepublic,Secrets,292642
1,SOUVTSM12AC468F6A7,Lil Wayne / Eminem,Drop The World,155717
2,SOPSOHT12A67AE0235,Randy Crawford,Almaz,129868
3,SOKLRPJ12A8C13C3FE,Coldplay,The Scientist,128837
4,SONQCXC12A6D4F6A37,Sheena Easton,Strut (1993 Digital Remaster),115134
5,SOXLOQG12AF72A2D55,Beastie Boys,Unite (2009 Digital Remaster),99137
6,SOPQLBY12A6310E992,Radiohead,Creep (Explicit),98854
7,SOSJRJP12A6D4F826F,Metallica,Master Of Puppets,98667
8,SOQZYQH12A8AE468E5,Cradle Of Filth,Better To Reign In Hell,88075
9,SOWEJXA12A6701C574,Coldplay,Fix You,84155

In [7]:
mr.train_als_model()
mr.precision_at_k() # Внимание: полная проверка модели ALS 10-20 минут

D:\miniconda\envs\ml\Lib\site-packages\implicit\cpu\als.py:95: RuntimeWarning: OpenBLAS is configured to use 8 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/998505 [00:00<?, ?it/s]

Precision@K: 0.1031

0.10311103963491891

### Люди, похожие на вас, слушают

In [3]:
user_id = 'b80344d063b5ccb3212f76538f3d9e43d87dca9e'
recommendations = mr.get_recommendations(user_id)
recommendations

               song_id              artist                           title
0   SOQGSUC12A8C13B66D            Colossal              Brave The Elements
1   SOCXCTS12AC468A380              The xx                     Basic Space
2   SOTMKZF12AB0187412              The xx                        Infinity
4   SOQLUTQ12A8AE48037        Foo Fighters                   The Pretender
5   SOXVVSM12A8C142224        Foo Fighters                        Everlong
7   SOQZYQH12A8AE468E5     Cradle Of Filth         Better To Reign In Hell
8   SONYKOW12AB01849C9         OneRepublic                         Secrets
9   SOAUDET12A6D4F96B7        Keisha White                         Brother
10  SOMCAFM12A58A7B024      Foolish Things                 Who Can Compare
11  SOTZION12A6D4FB477  Maroon 5 / Rihanna  If I Never See Your Face Again

### Люди, которые слушают этот трек, обычно слушают

In [4]:
item_id = 'SOAHOHL12A6D4F683A'
similar_items = mr.get_similar_items(item_id)
similar_items

,song_id,artist,title
1,SOJYHAP12A6D4F683E,Sister Hazel,Will Not Follow (Album Version)
2,SOUROMY12A6D4F6837,Sister Hazel,Dreamers (LP Version)
6,SOSTVDL12A6701E014,Eagle-Eye Cherry,This Paralysis
9,SOXSHEQ12A8C140E59,Better Than Ezra,Happy Day Mama (LP Version)
11,SOJKPHK12AB01864C0,Gin Blossoms,Someday Soon
12,SOTRVIF12AB0185FA4,Gin Blossoms,Fireworks
15,SOBRMZX12AC468666C,Eagle-Eye Cherry,If It Can't Be Found
18,SOFEGPP12A81C217B4,Better Than Ezra,"Tremble (From - Internet Only Release ""artifakt"")"
20,SODOHLU12A6D4F94C0,Fastball,I Get High (Album Version)
22,SORIHEU12A8C135099,Spin Doctors,Laraby's Gang

In [11]:
import gensim as pd
pd.__version__

'4.4.0'